name: create-jira-release
description: Create a release in Jira using Jira Automation Webhook
author: out-of-mana
inputs:
  webhook-url:
    description: Jira Automation Webhook URL
    required: true
  project: 
    description: The project you're cutting a release for
    default: ${{ github.event.repository.name }}
  release:
    description: Release tag (v1.0.0, 2.3.91, etc)
    default: ${{ github.event.release.tag_name }}
  tickets:
    description: List of Jira tickets to update from MERGED to DEPLOYED
    required: true
runs:
  using: docker
  image: Dockerfile
