name: create-jira-release
description: |
  Create a release in Jira using Jira Automation Webhook
author: out-of-mana
inputs: 
  webhook-url:
    description: Jira Automation Webhook URL
    required: true
  project: 
    description: Project to release
    required: true
  release: 
    description: A semantic version release tag (v1.0.0, v2.3.11, etc)
    required: true
  tickets:
    description: List of Jira tickets to update from MERGED to DEPLOYED
    required: true
outputs:
  output:
    description: The output
    value: ${{ steps.create-release.outputs.output }}
runs:
  using: "composite"
  steps:
    - name: Create release
      shell: bash
      id: create-release
      run: |
        OUTPUT="$(python ${GITHUB_WORKSPACE}/.github/actions/make-jira-release/app.py ${{ inputs.webhook-url }} ${{ inputs.project}}-${{ inputs.release }} ${{ inputs.tickets}})"
        echo "output=${OUTPUT}" >> $GITHUB_OUTPUT
