name: create-jira-release
description: Create a release in Jira using Jira Automation Webhook
author: out-of-mana
inputs:
  webhook-url:
    description: Jira Automation Webhook URL
    required: true
  tickets:
    description: List of Jira tickets to update from MERGED to DEPLOYED
    required: true
outputs:
  output:
    description: The output
    value: ${{ steps.create-release.outputs.output }}
runs:
  using: "composite"
  steps:
    - name: Create release
      shell: bash
      id: create-release
      run: |
        OUTPUT="$(python ${GITHUB_WORKSPACE}/.github/actions/make-jira-release/app.py ${{ inputs.webhook-url }} ${{ github.event.repository.name }}-${{ github.event.release.tag_name }} ${{ inputs.tickets}})"
        echo "output=${OUTPUT}" >> $GITHUB_OUTPUT
